name = "tg-traffic-bot"
main = "src/index.js"
compatibility_date = "2026-06-26"

[vars]
ADMIN_ID = "5947697192"
SITE_URL = "https://vk.com"
WORKER_URL = "https://minesdollar.site"
START_IMAGE = "https://ibb.co/b5vZmz5v"

[[d1_databases]]
binding = "DB"
database_name = "tg_traffic_bot"
database_id = "94f27ed3-ca8f-4775-8689-3261af16ea68"
